apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solarsystem-cert
  namespace: solar-system
spec:
  secretName: solarsystem-tls
  commonName: solarsystem.sysinfo.com
  dnsNames:
    - solarsystem.sysinfo.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 8760h   # 1 year
  renewBefore: 360h # renew 15 days before expiry
